import type { BusinessDetail } from "@/types/business";
import { DEFAULT_LANGUAGE, LANGUAGE_CODES } from "@/types/language";
import { z } from "zod";

/**
 * Zod schema for business form validation
 * Based on UpdateBusinessRequest type
 */
export const businessFormSchema = z.object({
  language: z.enum(LANGUAGE_CODES, { message: "El idioma es requerido" }),
  stateId: z.number().optional(),
  title: z.string().min(1, "El título es requerido"),
  inReccomended: z.boolean().optional(),
  inCalendar: z.boolean().optional(),
  ogTitle: z.string().optional(),
  ogDescription: z.string().optional(),
  keyWords: z.string().optional(),
  subtitle: z.string().nullable(),
  descriptionShort: z.string().optional(),
  subregionId: z.number().optional(),
  city: z.object({
    idCity: z.number().min(1, "La ciudad es requerida"),
  }),
  categories: z
    .array(z.object({ idCategory: z.number() }))
    .min(1, "Debe seleccionar al menos una categoría"),
  subcategories: z.array(z.object({ idCategory: z.number() })).optional(),
  forYou: z.boolean().nullable().optional(),
  outstanding: z.boolean().nullable().optional(),
  sponsored: z.boolean().nullable().optional(),
  location: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  latitude: z.number().nullable().optional(),
  longitude: z.number().nullable().optional(),
  description: z.string().nullable().optional(),
  // Additional fields for form state
  login: z.string().nullable().optional(),
  rawId: z.string().nullable().optional(),
  web: z.string().nullable().optional(),
  blog: z.string().nullable().optional(),
  instagramHandle: z.string().nullable().optional(),
  instagramUrl: z.string().nullable().optional(),
  priceRange: z.string().nullable().optional(),
  tipsThingsNotToMiss: z.string().nullable().optional(),
  cashRegisterId: z.string().nullable().optional(),
  limitTickets: z.string().nullable().optional(),
  buyNote: z.string().nullable().optional(),
  gatewayChannel: z.string().nullable().optional(),
  datesHours: z.string().nullable().optional(),
  roofTopTerrace: z.string().nullable().optional(),
  ticketsEntrance: z.string().nullable().optional(),
  rateStars: z.string().nullable().optional(),
  menuUrl: z.string().nullable().optional(),
  veganOptions: z.string().nullable().optional(),
  petFriendly: z.string().nullable().optional(),
  wheelchairAccessible: z.string().nullable().optional(),
  ageRestriction: z.string().nullable().optional(),
  datesHours2: z.string().nullable().optional(),
  guidedTours: z.string().nullable().optional(),
  suggestedVisitDuration: z.string().nullable().optional(),
  difficultyLevel: z.string().nullable().optional(),
  password: z.string().nullable().optional(),
  stateCheck: z.number().nullable().optional(),
  schedule: z.array(z.string()).nullable().optional(),
  youGoingWith: z.string().nullable().optional(),
  bestTimeOfTheYear: z.string().nullable().optional(),
  stayTime: z.string().nullable().optional(),
  mondayData: z.string().nullable().optional(),
  mondayLock: z.boolean().optional(),
  tuesdayData: z.string().nullable().optional(),
  tuesdayLock: z.boolean().optional(),
  wednesdayData: z.string().nullable().optional(),
  wednesdayLock: z.boolean().optional(),
  thursdayData: z.string().nullable().optional(),
  thursdayLock: z.boolean().optional(),
  fridayData: z.string().nullable().optional(),
  fridayLock: z.boolean().optional(),
  saturdayData: z.string().nullable().optional(),
  saturdayLock: z.boolean().optional(),
  sundayData: z.string().nullable().optional(),
  sundayLock: z.boolean().optional(),
  visibleWeb: z.boolean().optional(),
  visibleBlog: z.boolean().optional(),
  inCity: z.boolean().optional(),
  essential: z.boolean().optional(),
});

export type BusinessFormValues = z.infer<typeof businessFormSchema>;

const unavailableTextValues = new Set(["no disponible"]);

export function normalizeOptionalText(value: unknown): string | null {
  if (value == null) return null;

  const text = String(value).trim();
  if (!text || unavailableTextValues.has(text.toLocaleLowerCase("es"))) {
    return null;
  }

  return text;
}

export function normalizeBusinessFormValues(
  values: BusinessFormValues,
): BusinessFormValues {
  return {
    ...values,
    subtitle: normalizeOptionalText(values.subtitle),
    location: normalizeOptionalText(values.location),
    address: normalizeOptionalText(values.address),
    description: normalizeOptionalText(values.description),
    login: normalizeOptionalText(values.login),
    rawId: normalizeOptionalText(values.rawId),
    web: normalizeOptionalText(values.web),
    blog: normalizeOptionalText(values.blog),
    instagramHandle: normalizeOptionalText(values.instagramHandle),
    instagramUrl: normalizeOptionalText(values.instagramUrl),
    priceRange: normalizeOptionalText(values.priceRange),
    tipsThingsNotToMiss: normalizeOptionalText(values.tipsThingsNotToMiss),
    cashRegisterId: normalizeOptionalText(values.cashRegisterId),
    limitTickets: normalizeOptionalText(values.limitTickets),
    buyNote: normalizeOptionalText(values.buyNote),
    gatewayChannel: normalizeOptionalText(values.gatewayChannel),
    datesHours: normalizeOptionalText(values.datesHours),
    roofTopTerrace: normalizeOptionalText(values.roofTopTerrace),
    ticketsEntrance: normalizeOptionalText(values.ticketsEntrance),
    rateStars: normalizeOptionalText(values.rateStars),
    menuUrl: normalizeOptionalText(values.menuUrl),
    veganOptions: normalizeOptionalText(values.veganOptions),
    petFriendly: normalizeOptionalText(values.petFriendly),
    wheelchairAccessible: normalizeOptionalText(values.wheelchairAccessible),
    ageRestriction: normalizeOptionalText(values.ageRestriction),
    datesHours2: normalizeOptionalText(values.datesHours2),
    guidedTours: normalizeOptionalText(values.guidedTours),
    suggestedVisitDuration: normalizeOptionalText(values.suggestedVisitDuration),
    difficultyLevel: normalizeOptionalText(values.difficultyLevel),
    password: normalizeOptionalText(values.password),
    youGoingWith: normalizeOptionalText(values.youGoingWith),
    bestTimeOfTheYear: normalizeOptionalText(values.bestTimeOfTheYear),
    stayTime: normalizeOptionalText(values.stayTime),
    mondayData: normalizeOptionalText(values.mondayData),
    tuesdayData: normalizeOptionalText(values.tuesdayData),
    wednesdayData: normalizeOptionalText(values.wednesdayData),
    thursdayData: normalizeOptionalText(values.thursdayData),
    fridayData: normalizeOptionalText(values.fridayData),
    saturdayData: normalizeOptionalText(values.saturdayData),
    sundayData: normalizeOptionalText(values.sundayData),
  };
}

/**
 * Convert BusinessDetail to form values
 */
export function businessDetailToFormValues(
  business: BusinessDetail,
): BusinessFormValues {
  return normalizeBusinessFormValues({
    language: business.language || DEFAULT_LANGUAGE,
    stateId: business.stateId,
    title: business.title,
    inReccomended: business.inReccomended,
    inCalendar: business.inCalendar,
    ogTitle: business.ogTitle,
    ogDescription: business.ogDescription,
    keyWords: business.keyWords,
    subtitle: business.subtitle,
    descriptionShort: business.descriptionShort,
    subregionId: business.subregionId,
    city: {
      idCity: business.city.idCity,
    },
    categories: business.categories.map((cat) => ({
      idCategory: cat.idCategory,
    })),
    subcategories: business.subcategories.map((subcat) => ({
      idCategory: subcat.idCategory,
    })),
    forYou: business.forYou,
    outstanding: business.outstanding,
    sponsored: business.sponsored,
    location: business.location,
    address: business.address,
    latitude: business.latitude,
    longitude: business.longitude,
    description: business.description,
    login: business.login,
    rawId: business.rawId,
    web: business.web,
    blog: business.blog,
    instagramHandle: business.instagramHandle,
    instagramUrl: business.instagramUrl,
    priceRange: business.priceRange,
    tipsThingsNotToMiss: business.tipsThingsNotToMiss,
    cashRegisterId: business.cashRegisterId,
    limitTickets: business.limitTickets,
    buyNote: business.buyNote,
    gatewayChannel: business.gatewayChannel,
    datesHours: business.datesHours,
    roofTopTerrace: business.roofTopTerrace,
    ticketsEntrance: business.ticketsEntrance,
    rateStars: business.rateStars,
    menuUrl: business.menuUrl,
    veganOptions: business.veganOptions,
    petFriendly: business.petFriendly,
    wheelchairAccessible: business.wheelchairAccessible,
    ageRestriction: business.ageRestriction,
    datesHours2: business.datesHours2,
    guidedTours: business.guidedTours,
    suggestedVisitDuration: business.suggestedVisitDuration,
    difficultyLevel: business.difficultyLevel,
    password: business.password,
    stateCheck: business.stateCheck,
    schedule: Array.isArray(business.schedule) ? business.schedule : null,
    youGoingWith: business.youGoingWith,
    bestTimeOfTheYear:
      business.bestTimeOfTheYear != null
        ? String(business.bestTimeOfTheYear)
        : null,
    stayTime: business.stayTime != null ? String(business.stayTime) : null,
    mondayData: business.mondayData as string | null,
    mondayLock: business.mondayLock,
    tuesdayData: business.tuesdayData as string | null,
    tuesdayLock: business.tuesdayLock,
    wednesdayData: business.wednesdayData as string | null,
    wednesdayLock: business.wednesdayLock,
    thursdayData: business.thursdayData as string | null,
    thursdayLock: business.thursdayLock,
    fridayData: business.fridayData as string | null,
    fridayLock: business.fridayLock,
    saturdayData: business.saturdayData as string | null,
    saturdayLock: business.saturdayLock,
    sundayData: business.sundayData as string | null,
    sundayLock: business.sundayLock,
    visibleWeb: business.visibleWeb,
    visibleBlog: business.visibleBlog,
    inCity: business.inCity,
    essential: business.essential,
  });
}

/**
 * Get default form values for create mode
 */
export function getDefaultFormValues(): BusinessFormValues {
  return {
    language: DEFAULT_LANGUAGE,
    stateId: 1,
    title: "",
    inReccomended: true,
    inCalendar: false,
    ogTitle: "",
    ogDescription: "",
    keyWords: "",
    subtitle: null,
    descriptionShort: "",
    subregionId: 0,
    city: {
      idCity: 0,
    },
    categories: [],
    subcategories: [],
    forYou: false,
    outstanding: false,
    sponsored: false,
    location: "",
    address: null,
    latitude: 0,
    longitude: 0,
    description: "",
    login: "",
    rawId: "",
    web: "",
    blog: null,
    instagramHandle: null,
    instagramUrl: null,
    priceRange: null,
    tipsThingsNotToMiss: null,
    cashRegisterId: null,
    limitTickets: null,
    buyNote: null,
    gatewayChannel: null,
    datesHours: null,
    roofTopTerrace: null,
    ticketsEntrance: null,
    rateStars: null,
    menuUrl: null,
    veganOptions: null,
    petFriendly: null,
    wheelchairAccessible: null,
    ageRestriction: null,
    datesHours2: null,
    guidedTours: null,
    suggestedVisitDuration: null,
    difficultyLevel: null,
    password: "",
    stateCheck: 0,
    schedule: null,
    youGoingWith: "",
    bestTimeOfTheYear: null,
    stayTime: null,
    mondayData: null,
    mondayLock: false,
    tuesdayData: null,
    tuesdayLock: false,
    wednesdayData: null,
    wednesdayLock: false,
    thursdayData: null,
    thursdayLock: false,
    fridayData: null,
    fridayLock: false,
    saturdayData: null,
    saturdayLock: false,
    sundayData: null,
    sundayLock: false,
    visibleWeb: false,
    visibleBlog: false,
    inCity: false,
    essential: false,
  };
}
