import type { Section } from '../editorial-template'

/**
 * A ToolAdapter transforms the raw `result_data` JSON generated by Claude
 * for a toolkit tool into the Section[] consumed by the editorial template.
 * Adapters MUST be defensive: real data may deviate from the prompt contract
 * (missing keys, strings instead of arrays, unexpected nesting) and an
 * adapter must never throw.
 */
export type ToolAdapter = (result: Record<string, any>) => Section[]
