/**
 * Hardcoded fallback copy for the home page — the "flat-fields" shape this
 * mirrors 1:1 in SF-CMS (project: discoolver, page slug: home, section id:
 * "content", type: flat-fields). Every key here is a candidate CMS field.
 * scripts/fetch-cms-content.mjs bakes CMS overrides into content/pages.json
 * at build time; lib/cms-pages.ts#mergeContent() merges them over this
 * object so a CMS outage (or an empty field) never breaks the page — the
 * hardcoded value here always renders.
 */
export const defaultHomeContent = {
  // Hero
  hero_eyebrow: "Solo por invitación · 500 plazas / ciudad · app coming soon",
  hero_title_line1: "Enjoy like a",
  hero_title_highlight1: "local.",
  hero_title_line2: "Discover like",
  hero_title_line3: "an",
  hero_title_highlight2: "animal.",
  hero_sub:
    "Tus instintos nacieron para explorar. Discoolver desbloquea el lado salvaje de la ciudad — curado por creadores reales y potenciado por IA. Entra hoy por la web con tu código. La app llega",
  hero_sub_strong: "muy pronto.",
  hero_stat1_num: "500",
  hero_stat1_label: "plazas / ciudad",
  hero_stat2_num: "12",
  hero_stat2_label: "ciudades activas",
  hero_stat3_num: "42",
  hero_stat3_label: "curators locales",
  hero_stat4_num: "app",
  hero_stat4_label: "muy pronto · iOS / Android",
  hero_social_count: "8742",
  hero_social_label: "personas ya en lista",
  hero_social_live: "● 247 entraron esta semana",
  hero_visual_pill: "● Madrid · ahora mismo",
  hero_visual_title: "Cool Map · 4 planes cerca de ti",

  // Ticker
  ticker_1: "Madrid · 217 plazas restantes",
  ticker_2: "Concierto sorpresa en Malasaña",
  ticker_3: "Barcelona · 89 plazas restantes",
  ticker_4: "Ruta de tapas · 7 paradas",
  ticker_5: "Sevilla · 412 plazas restantes",
  ticker_6: "Cinema bajo las estrellas",
  ticker_7: "Valencia · 333 plazas restantes",
  ticker_8: "Cata de vinos naturales",
  ticker_9: "Bilbao · 156 plazas restantes",
  ticker_10: "Free-tour barrios olvidados",

  // Categories (bento)
  categories_eyebrow: "Categorías · 06",
  categories_title: "Encuentra",
  categories_title_highlight: "tu vibra.",
  categories_lead: "Seis universos para explorar la ciudad. Cada plan está verificado por un curator local.",
  categories_cta: "Ver todas",
  cat_1_name: "Gastronomía",
  cat_1_highlight: "sabores",
  cat_1_count: "412 planes",
  cat_2_name: "Cultura",
  cat_2_highlight: "viva",
  cat_2_count: "186",
  cat_3_name: "Aire",
  cat_3_highlight: "libre",
  cat_3_count: "247",
  cat_4_name: "Night",
  cat_4_highlight: "life",
  cat_4_count: "98 planes",
  cat_5_name: "Familia",
  cat_5_count: "163",
  cat_6_name: "Compras",
  cat_6_count: "274",

  // Travel brain (smart card)
  travel_brain_eyebrow: "No es otra app de reseñas",
  travel_brain_badge: "◉ Demo · Smart Card",
  travel_brain_title_1: "We're not another review app.",
  travel_brain_title_2: "We're your",
  travel_brain_title_highlight: "travel brain.",
  travel_brain_bullet_1: "Curamos lo mejor de blogs, redes y creadores — sin rankings de pago.",
  travel_brain_bullet_2: "La IA personaliza según tu ciudad, fechas y estilo de viaje.",
  travel_brain_bullet_3: "Te saltas las horas de búsqueda. Reservas al instante.",
  travel_brain_bullet_4: "Desde azoteas hasta cenas secretas. Evitas trampas turísticas. Siempre.",
  travel_brain_quote: "Smart suggestions. Real vibes. Zero BS.",

  // How it works (steps)
  how_it_works_eyebrow: "Tus armas secretas en la ciudad",
  how_it_works_title_1: "No es una guía. No es un blog.",
  how_it_works_title_2: "Es un",
  how_it_works_title_highlight: "sexto sentido",
  how_it_works_title_3: "para experiencias reales.",
  step_1_title: "Cool Map",
  step_1_desc: "Solo los 10 sitios. Sin ruido. Just gold. Curado a mano, no clickbait — navega como local, no como turista.",
  step_2_title: "Plan My Trip",
  step_2_desc: "Cuéntanos tus fechas, presupuesto y vibra. Construimos tu ruta 100% personalizada. Cero tiempo perdido.",
  step_3_title: "Smart Calendar",
  step_3_desc: "Eventos en tiempo real, alertas, recordatorios. Sintonizado con tu agenda — saber qué pasa ya.",
  step_4_title: "Local Buddy AI",
  step_4_desc: "Pregúntale lo que sea, como a un colega de toda la vida. Tu sexto sentido digital 24/7.",

  // Experiences
  experiences_eyebrow: "Experiencias destacadas",
  experiences_title: "Planes con",
  experiences_title_highlight: "chispa",
  experiences_title_2: "esta semana.",
  exp_1_badge: "Top de la semana",
  exp_1_cat: "Cultura",
  exp_1_title: "Arte y misterio en los museos",
  exp_1_rating: "4.9",
  exp_1_reviews: "312",
  exp_1_price: "18 €",
  exp_2_badge: "Nuevo",
  exp_2_cat: "Gastro",
  exp_2_title: "Cena con encanto local",
  exp_2_rating: "4.8",
  exp_2_reviews: "198",
  exp_2_price: "Gratis",
  exp_3_badge: "Plan estrella",
  exp_3_cat: "Cultura",
  exp_3_title: "Ciudades de película",
  exp_3_rating: "4.9",
  exp_3_reviews: "244",
  exp_3_price: "29 €",
  exp_4_badge: "Sábados",
  exp_4_cat: "Nightlife",
  exp_4_title: "Noche en el estadio",
  exp_4_rating: "4.7",
  exp_4_reviews: "156",
  exp_4_price: "22 €",
  exp_5_badge: "Plazas: 6",
  exp_5_cat: "Aire libre",
  exp_5_title: "Metro tour nocturno",
  exp_5_rating: "4.8",
  exp_5_reviews: "89",
  exp_5_price: "Gratis",
  exp_6_badge: "Local pick",
  exp_6_cat: "Cultura",
  exp_6_title: "Escapada VIP al siguiente nivel",
  exp_6_rating: "5",
  exp_6_reviews: "47",
  exp_6_price: "35 €",

  // Map
  map_eyebrow: "Mapa interactivo",
  map_title: "La ciudad",
  map_title_highlight: "cabe",
  map_title_2: "en tu bolsillo.",
  map_lead: "Filtros por barrio, hora y vibra. Guardas tus pins y los compartes con quien quieras.",
  map_cta: "Abrir mapa completo",
  map_pin_1_cat: "Gastronomía",
  map_pin_1_name: "Mercado de San Fernando",
  map_pin_2_cat: "Cultura",
  map_pin_2_name: "Azotea del Círculo",
  map_pin_3_cat: "Aire libre",
  map_pin_3_name: "Parque del Capricho",
  map_pin_4_cat: "Nightlife",
  map_pin_4_name: "Macera Taller",
  map_pin_5_cat: "Cultura",
  map_pin_5_name: "Lavapiés Streetart",
  map_popup_desc: "Vistas 360º de la ciudad y un sunset que vale la entrada.",

  // For creators
  creators_eyebrow: "Para creators · invite-only",
  creators_title_1: "Not a tourist. Not a follower.",
  creators_title_highlight: "A creator.",
  creators_lead:
    "No solo viajas. Influyes en cómo viajan los demás. Convierte tus rutas en historias que pagan — con links únicos, tracking real y comisión por venta.",
  creators_cta: "Apply as creator",
  creator_value_1_title: "Monetizable",
  creator_value_1_desc: "Gana por cada venta generada con tu contenido. Tracking real.",
  creator_value_2_title: "Personalizado",
  creator_value_2_desc: "Tu audiencia ve experiencias hechas para ellos, no listas genéricas.",
  creator_value_3_title: "Localizado",
  creator_value_3_desc: "Mapas, calendarios y rutas con tus recomendaciones.",
  creator_value_4_title: "Escalable",
  creator_value_4_desc: "Llega a viajeros de todo el mundo y crece tu comunidad.",

  // App coming soon
  app_soon_eyebrow: "App coming soon · iOS + Android",
  app_soon_title_1: "La app llega en",
  // El número lo pone el componente desde LAUNCH_DATE (ver Countdown.tsx).
  // No lo devuelvas a un campo del CMS: se queda congelado y contradice al
  // contador que tiene justo debajo.
  app_soon_title_2: "días.",
  app_soon_title_3: "Tu acceso ya está reservado.",
  app_soon_desc:
    "Mapa offline, calendario inteligente, Local Buddy AI en tu bolsillo y rutas hechas para ti en 10 segundos. Los que estén en la lista entran primero — y reciben un mes premium gratis.",
  app_soon_cta: "Avísame al lanzamiento",
  app_soon_sticker: "in {days} days",

  // Testimonials
  testimonials_eyebrow: "Lo que dicen los descubridores",
  // Antes: "120.000 personas redescubren su ciudad cada semana". Cifra sin
  // respaldo, y además incompatible con el resto de la página (8.742 en lista,
  // 500 plazas × 12 ciudades). El titular ahora dice algo cierto y que sale de
  // las propias citas: quienes las escriben llevan años en su ciudad.
  testimonials_title: "Llevan años en su ciudad.",
  testimonials_title_highlight: "Y siguen descubriendo.",
  testimonial_1_quote: "Llevo 12 años en Madrid y descubrí 3 sitios nuevos en una tarde. Brujería.",
  testimonial_1_name: "Lucía M.",
  testimonial_1_role: "Diseñadora · Madrid",
  testimonial_2_quote: "La app que necesitaba para no parecer turista en mi propia ciudad.",
  testimonial_2_name: "Andrés P.",
  testimonial_2_role: "Local · Sevilla",
  testimonial_3_quote: "Los planes son raros en el buen sentido — nada de cosas obvias de TripAdvisor.",
  testimonial_3_name: "Marta G.",
  testimonial_3_role: "Curator · BCN",
  testimonial_4_quote: "Mi novio me pide que le sorprenda y siempre tiro de Discoolver. Sale el héroe yo.",
  testimonial_4_name: "Iván R.",
  testimonial_4_role: "Madrid",
  testimonial_5_quote: "Curaduría real, no listicles. Eso vale oro.",
  testimonial_5_name: "Sofía T.",
  testimonial_5_role: "Periodista · Bilbao",
  testimonial_6_quote: "El mapa es adictivo. Salí a por el pan y volví con 4 fotos nuevas.",
  testimonial_6_name: "Carmen L.",
  testimonial_6_role: "Madrid",

  // FAQ
  faq_eyebrow: "Preguntas frecuentes",
  faq_title_1: "Antes de que nos",
  faq_title_highlight: "preguntes.",
  faq_lead_pre: "Si no encuentras tu respuesta, escríbenos a",
  faq_lead_email: "hola@discoolver.com",
  faq_lead_post: ". Respondemos en menos de 12 h.",
  faq_q1: "¿Qué es exactamente Discoolver?",
  faq_a1:
    "Una plataforma local con curaduría humana + IA que te enseña los planes, rincones y eventos que realmente merecen la pena de tu ciudad. Sin rankings de pago, sin trampas turísticas. Hoy se accede por la web; la app llega muy pronto.",
  faq_q2: "¿Cómo consigo mi invitación?",
  faq_a2: "Déjanos tu email y tu ciudad en el formulario del hero. En menos de 24 h recibes tu código personal. Hay 500 plazas por ciudad en esta primera oleada.",
  faq_q3: "¿Cuándo lanzáis la app?",
  faq_a3: "Estamos en sprint final. Si estás en la lista, entras primero — y te regalamos un mes premium completo. Suscríbete arriba para recibir el aviso justo el día del lanzamiento.",
  faq_q4: "¿En qué ciudades funciona?",
  faq_a4: "Empezamos con 12: Madrid, Barcelona, Sevilla, Valencia, Bilbao, Málaga, Zaragoza, Granada, San Sebastián, Palma, Toledo y Córdoba. Las siguientes oleadas las decidirá la comunidad.",
  faq_q5: "¿Cuánto cuesta?",
  faq_a5:
    "Tener cuenta y usar el mapa, gratis. La membresía premium (rutas IA ilimitadas, eventos privados, ventajas en partners) cuesta menos que un café al mes — y tu primer mes va de nuestra parte si entras desde la lista.",
  faq_q6: "Soy creator local, ¿cómo participo?",
  faq_a6:
    'Tenemos un programa de creators por invitación con tracking de ventas, comisión por cada experiencia que cierres y herramientas para construir tu marca personal. Hay un botón "Apply as creator" en la sección de creators.',
  faq_q7: "Soy negocio o ayuntamiento. ¿Hay algo para mí?",
  faq_a7: 'Sí. Tenemos un programa B2B con dashboard de visibilidad, campañas locales y partnerships exclusivos. Escríbenos desde la sección "Para empresas" del menú.',

  // CTA
  cta_eyebrow: "Acceso por invitación · web abierta hoy · app muy pronto",
  cta_title_1: "Pide tu",
  cta_title_1_em: "código.",
  cta_title_2: "Entra",
  cta_title_2_em: "antes",
  cta_title_3: "que el resto.",
  cta_sub: "Solo 500 plazas por ciudad en esta primera oleada. Hoy entras a Discoolver desde la web; cuando lance la app, tendrás acceso prioritario y un mes premium gratis.",
  cta_primary: "Pedir mi invitación",
  cta_secondary: "Para empresas",
  cta_cities: "Madrid · Barcelona · Sevilla · Valencia · Bilbao · Málaga · Zaragoza · Granada · San Sebastián · Palma · Toledo · Córdoba",

  // Footer
  footer_brand_desc: "La plataforma para descubrir tu ciudad como nunca antes lo habías hecho.",
  footer_copyright: "Discoolver · Hecho con ♥ desde España",
} as const;

export type HomeContent = { -readonly [K in keyof typeof defaultHomeContent]: string };
