import type { Metadata } from 'next'
import Link from 'next/link'
import { AlertTriangle } from 'lucide-react'
import MiraLogo from '@/components/mira-logo'

export const metadata: Metadata = {
  title: 'Terms of Service — MIRA',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-page">
      <header className="border-b border-line-subtle">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/login" className="flex items-center gap-2">
            <MiraLogo size={22} variant="icon" />
            <span className="text-sm font-bold text-ink">MIRA</span>
          </Link>
          <nav className="flex items-center gap-4 text-xs text-ink-tertiary">
            <Link href="/terms" className="text-ink">Terms</Link>
            <Link href="/privacy" className="hover:text-ink">Privacy</Link>
            <Link href="/cookies" className="hover:text-ink">Cookies</Link>
          </nav>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10">
        <div className="mb-8 flex items-start gap-3 rounded-xl border px-4 py-3"
          style={{ background: 'rgba(245,158,11,0.1)', borderColor: 'rgba(245,158,11,0.3)' }}>
          <AlertTriangle size={16} className="mt-0.5 shrink-0" style={{ color: '#fbbf24' }} />
          <p className="text-xs font-medium leading-relaxed" style={{ color: '#fbbf24' }}>
            Legal template — review with a lawyer before publishing. It does not replace professional legal advice.
          </p>
        </div>

        <h1 className="text-2xl font-semibold text-ink tracking-tight mb-1">Terms of Service</h1>
        <p className="text-xs text-ink-tertiary mb-8">Last updated: July 23, 2026</p>

        <div className="space-y-7 text-sm text-ink-secondary leading-relaxed">
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">1. Purpose and acceptance</h2>
            <p>
              These Terms of Service govern the access to and use of MIRA, a SaaS platform that provides a
              team of artificial intelligence agents to automate marketing, sales, strategy, operations and
              finance tasks for your business (&quot;the Service&quot;), operated by Startup Factory
              (&quot;we&quot;, &quot;MIRA&quot;). By creating an account or using the Service you accept these
              terms. If you do not agree, you must not use MIRA.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">2. Description of the service</h2>
            <p>
              MIRA provides AI agents organized by department (marketing, sales, strategy, operations and
              finance) that generate content, analyses, reports and recommendations based on your business
              information and your instructions. MIRA is currently in beta: some features may change, fail
              occasionally or be incomplete.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">3. Registration and user account</h2>
            <p>
              To use MIRA you need to create an account with accurate information and keep it up to date. You
              are responsible for the confidentiality of your credentials and for all activity that occurs
              under your account. Notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">4. Acceptable use</h2>
            <p>
              You agree not to use MIRA for illegal purposes, to generate content that is defamatory,
              misleading, fraudulent or that infringes third-party rights, or to attempt to gain unauthorized
              access to systems, other customers&apos; data or the Service&apos;s infrastructure.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">5. Your content</h2>
            <p>
              All content you upload or connect to MIRA (brand documents, business information, briefs,
              connections to external tools) remains yours. You grant us a limited license to store and
              process that content for the sole purpose of providing the Service to you, including its use as
              context for the AI agents to generate results.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">6. AI-generated results</h2>
            <p>
              The texts, reports, analyses and images generated by MIRA&apos;s agents are produced by
              artificial intelligence models and may contain errors, inaccuracies or biases. You are
              responsible for reviewing and validating any result before using it, publishing it or making
              business decisions based on it.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">7. Plans, pricing and billing</h2>
            <p>
              MIRA is offered under different subscription plans. As the product is in beta, the pricing,
              usage limits and features included in each plan may change; we will give you reasonable advance
              notice of changes that affect you as an active customer.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">8. Service availability</h2>
            <p>
              We work to keep MIRA continuously available, but as a beta product we do not guarantee a
              specific service level (SLA) or the complete absence of interruptions or errors.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">9. Intellectual property</h2>
            <p>
              The MIRA platform, its brand, design, code and AI agents are the property of Startup Factory.
              Nothing in these terms transfers any rights over them to you beyond the license to use the
              Service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">10. Limitation of liability</h2>
            <p>
              The Service is provided &quot;as is&quot;, especially during this beta phase. To the extent
              permitted by law, MIRA shall not be liable for indirect damages or loss of business arising from
              the use of the Service or from decisions made based on the results generated by the AI agents.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">11. Suspension and termination</h2>
            <p>
              You can cancel your account at any time by contacting us. We may suspend or terminate accounts
              that breach these terms, with prior notice except in serious or urgent cases.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">12. Changes to these terms</h2>
            <p>
              We may update these Terms of Service to reflect changes in the product or in applicable
              regulations. We will publish the date of the latest update on this same page.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">13. Governing law and jurisdiction</h2>
            <p>
              These terms are governed by the laws of [Spain]. Any dispute shall be submitted to the competent
              courts and tribunals in accordance with such laws.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-ink mb-2">14. Contact</h2>
            <p>
              For any questions about these terms, write to us at [contacto@startupsfactory.es].
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
