/**
 * CMS posts helper — reads content/posts.json (generated by fetch-cms-content.mjs)
 * Pattern: same as cms-pages.ts for safety (require + try/catch, returns [] if missing).
 * Maps the camelCase JSON shape to the snake_case shape the pages consume.
 */

export interface CmsPost {
  id: string
  slug: string
  title: string
  excerpt?: string
  content_html?: string
  cover_url?: string
  category?: string
  author_name?: string
  published_at?: string
  seo_title?: string
  seo_description?: string
  og_image_url?: string
}

interface RawPost {
  id: string
  slug: string
  title: string
  excerpt?: string
  contentHtml?: string
  coverUrl?: string
  category?: string
  author?: string
  date?: string
  seoTitle?: string
  seoDescription?: string
  ogImage?: string
}

function loadPosts(): CmsPost[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const raw: RawPost[] = require('../../content/posts.json')
    return raw.map((p) => ({
      id: p.id,
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt,
      content_html: p.contentHtml,
      cover_url: p.coverUrl,
      category: p.category,
      author_name: p.author,
      published_at: p.date,
      seo_title: p.seoTitle,
      seo_description: p.seoDescription,
      og_image_url: p.ogImage,
    }))
  } catch {
    return []
  }
}

export async function getPosts(): Promise<CmsPost[]> {
  return loadPosts()
}

export async function getPostBySlug(slug: string): Promise<CmsPost | null> {
  const posts = loadPosts()
  return posts.find((p) => p.slug === slug) || null
}
