/**
 * CMS pages helper — reads content/pages.json (generated by fetch-cms-content.mjs)
 * and exposes typed helpers per section and language.
 *
 * Usage:
 *   import { getCmsHome } from '@/lib/cms-pages'
 *   const home = getCmsHome('en')
 *   home.hero.headline1  // CMS content, falls back to undefined if not loaded
 */

import type { Lang } from './translations'

// ── Types ──────────────────────────────────────────────────
export interface CmsHero {
  badge: string
  headline1: string
  headline2: string
  sub: string
  badge1: string
  badge2: string
}

export interface CmsSauceItem {
  name: string
  desc: string
  heat: number
}

export interface CmsSauces {
  eyebrow: string
  title1: string
  title2: string
  count: string
  countSub: string
  sauces: CmsSauceItem[]
}

export interface CmsDelivery {
  eyebrow: string
  title: string
  sub: string
  btn_grab: string
  btn_line: string
}

export interface CmsFinalCta {
  badge: string
  headline1: string
  sub: string
  btn_grab: string
  btn_line: string
}

export interface CmsSeo {
  seo_title: string
  seo_description: string
  og_image: string
  keywords: string
}

export interface CmsHome {
  hero:      CmsHero | null
  sauces:    CmsSauces | null
  delivery:  CmsDelivery | null
  finalCta:  CmsFinalCta | null
  seo:       CmsSeo | null
}

// ── Load pages.json (server-side only) ────────────────────
function loadPages(): Record<string, { sections: Record<string, unknown> }> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('../../content/pages.json')
  } catch {
    return {}
  }
}

// Pick a multilang value: data.key_en / data.key_th / data.key_es
function pick(data: Record<string, unknown>, key: string, lang: Lang): string {
  const val = (data[`${key}_${lang}`] ?? data[`${key}_en`] ?? '') as string
  return val
}

// ── Public helper ─────────────────────────────────────────
export function getCmsHome(lang: Lang): CmsHome {
  const pages = loadPages()
  const home = pages['home']
  if (!home) return { hero: null, sauces: null, delivery: null, finalCta: null, seo: null }

  const sections = home.sections as Record<string, { type: string; data: Record<string, unknown> }>

  // ── hero ──
  let hero: CmsHero | null = null
  const heroSection = sections['hero']
  if (heroSection?.data) {
    const d = heroSection.data
    hero = {
      badge:     pick(d, 'badge', lang),
      headline1: pick(d, 'headline1', lang),
      headline2: pick(d, 'headline2', lang),
      sub:       pick(d, 'sub', lang),
      badge1:    pick(d, 'badge1', lang),
      badge2:    pick(d, 'badge2', lang),
    }
  }

  // ── sauces ──
  let sauces: CmsSauces | null = null
  const saucesSection = sections['sauces']
  if (saucesSection?.data) {
    const d = saucesSection.data
    sauces = {
      eyebrow:  pick(d, 'eyebrow', lang),
      title1:   pick(d, 'title1', lang),
      title2:   pick(d, 'title2', lang),
      count:    pick(d, 'count', lang),
      countSub: pick(d, 'countSub', lang),
      sauces:   Array.isArray(d.sauces) ? d.sauces as CmsSauceItem[] : [],
    }
  }

  // ── delivery ──
  let delivery: CmsDelivery | null = null
  const deliverySection = sections['delivery']
  if (deliverySection?.data) {
    const d = deliverySection.data
    delivery = {
      eyebrow:  pick(d, 'eyebrow', lang),
      title:    pick(d, 'title', lang),
      sub:      pick(d, 'sub', lang),
      btn_grab: pick(d, 'btn_grab', lang),
      btn_line: pick(d, 'btn_line', lang),
    }
  }

  // ── final-cta ──
  let finalCta: CmsFinalCta | null = null
  const ctaSection = sections['final-cta']
  if (ctaSection?.data) {
    const d = ctaSection.data
    finalCta = {
      badge:     pick(d, 'badge', lang),
      headline1: pick(d, 'headline1', lang),
      sub:       pick(d, 'sub', lang),
      btn_grab:  pick(d, 'btn_grab', lang),
      btn_line:  pick(d, 'btn_line', lang),
    }
  }

  // ── seo ──
  let seo: CmsSeo | null = null
  const seoSection = sections['seo']
  if (seoSection?.data) {
    const d = seoSection.data
    seo = {
      seo_title:       (d.seo_title as string) ?? '',
      seo_description: (d.seo_description as string) ?? '',
      og_image:        (d.og_image as string) ?? '',
      keywords:        (d.keywords as string) ?? '',
    }
  }

  return { hero, sauces, delivery, finalCta, seo }
}
