/**
 * CMS posts helper — reads content/posts.json (generated by fetch-cms-content.mjs)
 * Pattern: same as cms-pages.ts for safety (require + try/catch, returns [] if missing)
 */

export interface CmsPost {
  id: string
  slug: string
  title: string
  excerpt?: string
  contentHtml?: string
  category?: string
  author?: string
  date?: string
  seoTitle?: string
  seoDescription?: string
  ogImage?: string
}

function loadPosts(): CmsPost[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('../content/posts.json')
  } catch {
    return []
  }
}

export async function getPosts(): Promise<CmsPost[]> {
  return loadPosts()
}

export async function getPost(slug: string): Promise<CmsPost | null> {
  const posts = loadPosts()
  return posts.find((p) => p.slug === slug) || null
}
