/**
 * CMS posts helper — reads content/posts.json (generated by fetch-cms-content.mjs)
 * Pattern: same as cms-pages.ts for safety (require + try/catch, returns [] if missing).
 * Maps the camelCase JSON shape to the snake_case shape the pages consume.
 */

export interface CmsPost {
  id: string
  title: string
  slug: string
  excerpt: string | null
  cover_url: string | null
  content_html: string | null
  category: string | null
  author_name: string | null
  published_at: string | null
  seo_title: string | null
  seo_description: string | null
  og_image_url: string | null
}

interface RawPost {
  id: string
  slug: string
  title: string
  excerpt?: string
  contentHtml?: string
  coverUrl?: string
  category?: string
  author?: string
  date?: string
  seoTitle?: string
  seoDescription?: string
  ogImage?: string
}

function loadPosts(): CmsPost[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const raw: RawPost[] = require('../content/posts.json')
    return raw.map((p) => ({
      id: p.id,
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt ?? null,
      content_html: p.contentHtml ?? null,
      cover_url: p.coverUrl ?? null,
      category: p.category ?? null,
      author_name: p.author ?? null,
      published_at: p.date ?? null,
      seo_title: p.seoTitle ?? null,
      seo_description: p.seoDescription ?? null,
      og_image_url: p.ogImage ?? null,
    }))
  } catch {
    return []
  }
}

export async function getPosts(): Promise<CmsPost[]> {
  return loadPosts()
}

export async function getPost(slug: string): Promise<CmsPost | null> {
  const posts = loadPosts()
  return posts.find((p) => p.slug === slug) || null
}
